@startuml

package api {
  class MangaRegisterApi {
    + register()
  }
}

package service {
  class MangaRegisterService {
    + 漫画 refer()
    + register(Manga)
  }
}

package domain {
  interface Repository {
    + 漫画 refer()
    + register(Manga)
  }
  package domain.manga {
    class 漫画 {
      漫画コード
      タイトル
      ジャンル
    }
    class タイトル {
      タイトル名
      巻数
    }
    class ジャンル {
    }

    漫画 --> タイトル
    漫画 --> ジャンル

    Repository --> 漫画
  }
}

package datasource {
  class RepositoryEvent {
  }
}

MangaRegisterApi --> MangaRegisterService
MangaRegisterService --> 漫画
MangaRegisterService --> Repository
RepositoryEvent --|> Repository

@enduml